services:

  datomic-transactor:
    build: ./docker/transactor
    environment:
      BOOT_CONFIG_EDN: /usr/config/dev/config.edn
    volumes:
      - ./config:/usr/config
    ports:
      - '4334:4334'

  datomic-peer-server:
    build: ./docker/peer-server
    environment:
      PORT: 8998
      DATOMIC_ACCESS_KEY: unsafe-key
      DATOMIC_SECRET: unsafe-secret
      DATOMIC_DATABASE: my-datomic-database
      DATOMIC_STORAGE_URI: datomic:dev://datomic-transactor:4334/my-datomic-database/?password=unsafe
    ports:
      - 8998:8998

  datomic-console:
    build: ./docker/console
    environment:
      DB_URI: datomic:dev://datomic-transactor:4334/?password=unsafe
    ports:
      - '8081:8080'

  datomic-tools:
    build: ./docker/tools
